<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
  <!ELEMENT marcadores (marcador)*> 
  <!ELEMENT marcador (nombre, uri)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT uri (#PCDATA)>
]>

<marcadores>
  <marcador>
    <nombre>W3C</nombre>
    <uri>http://www.w3.org/</uri>
  </marcador>
  <marcador>
    <nombre>Web Hypertext Application Technology Working Group</nombre>
    <uri>http://www.whatwg.org/</uri>
  </marcador>
</marcadores>

<!-- Como no existe el elemento favoritos cambiamos el DOCTYPE y lo redefinimos como marcadores. Además marcadores podrá contneer 0, 1 o varios
 elementos marcador -->