<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
<!ELEMENT colores (color)*>
<!ELEMENT color (nombreSvg, codigo)>
<!ELEMENT codigo (rgb | cmyk)>
<!ELEMENT nombreSvg (#PCDATA)>
<!ELEMENT rgb (#PCDATA)>
<!ELEMENT cmyk (#PCDATA)>
]>
<colores>
  <color>
    <nombreSvg>Purple</nombreSvg>
    <codigo>
      <rgb>#800080</rgb>
    </codigo>
  </color>
  <color>
    <nombreSvg>Purple</nombreSvg>
    <codigo>
      <cmyk>#00FF007F</cmyk>
    </codigo>
  </color>
</colores>

<!-- En el DTD definimos el elemento color para que este formado por los elementos nombreSVg y codigo. También definimos el elemento codigo para que esté
formado por el elemento rgb o el elemento cmyk -->